---
- hosts: instance1
  gather_facts: true
  tasks:
  - name: copying the dir and contents
    become: true
    copy:
     src: /var/www/html/html5-simple-personal-website/
     dest: /var/www/html/
     owner: root
     group: root
     mode: 0644
  - name: updating index.html
    template:
      src: ./index.html.j2
      dest: /var/www/html/index.html
      mode: 0777
  