---
- hosts: instance1
  gather_facts: true
  vars:
    config_file: "{{ lookup('file','{{playbook_dir}}/config.json') | from_json }}"
  tasks:
  - name: copying the dir and contents
    become: true
    copy:
     src: /var/www/html/html5-simple-personal-website/
     dest: /var/www/html/
     owner: root
     group: root
     mode: 0644
  - name: updating index.html
    become: true
    template:
      src: ./index.html.j2
      dest: /var/www/html/index.html
      mode: 0777
    vars:
     name: "{{ config_file.name }}"
  